### ISSUE TITLE
AlignCommodity wrong alignment

### ISSUE THREAD

**Issue by yegle** [nathangrigg/vim-beancount#14]
For a transaction like this:
```
2015-08-25 * "Investment"
    Assets:Wealthfront:SCHB            7 SCHB {49.99 USD, 2015-08-20}
```

`AlignCommodity` will use the decimal point in the price `49.99` instead of the imaginary decimal point after `7`

**Comment by nathangrigg** [comment]
I'm aware of this and wouldn't be too hard to fix, if I find the time :)
