### ISSUE TITLE
Payee completion

### ISSUE THREAD

**Issue by yegle** [nathangrigg/vim-beancount#16]
Would love to see the ability to complete payee names.

**Comment by nathangrigg** [comment]
Agree that this would be great.

Right now, the completion engine only reads the file once per vim session. For accounts, this is generally okay, but I feel like for payees it would become more glaring.

So I feel like I should update the completion engine to reparse the file more often, but then I should make it async, and that is a rabbit hole. 

Maybe it is worth just adding rudimentary support.

**Comment by xentac** [comment]
I considered this one.  I have a bunch of changes that add support for other things.  As it stands right now I support completion for a lot more things (commodity, directives, tags, links) following a similar approach to what was there previously.

I'm also a bit more worried about how much more memory it will take to extract every unique payee from the entire file.  I'll explore this in the future.
