### ISSUE TITLE
Autocompletion only works on accounts

### ISSUE THREAD

**Issue by xentac** [nathangrigg/vim-beancount#20]
I'd really like it if it worked on at least tag, links, and currencies as well.

I have plans to rewrite the account finder to use bean-query and implement similar loaders for tags, links, curriences, and anything else I can think of.

Hopefully you are amenable to this.

**Comment by xentac** [comment]
I'd like to complete a lot of different strings as well, but they're harder.

I'd want to at least complete event strings (the location part of "YYYY-MM-DD event "location" "New York, USA"").

**Comment by nathangrigg** [comment]
I am definitely open to this, and bean-query is the way to go, better than parsing the file manually as I  am doing now.

See also #16 asking for payee support.

**Comment by xentac** [comment]
My first cut is https://github.com/xentac/vim-beancount/tree/improved_autocomplete but I haven't really had a chance to vet it, so I'm not making a pull request yet.

It supports tags, links, commodities, and directives.

**Comment by xentac** [comment]
I'll look into payees a little later.  I agree that updating the complete lists async would be really cool, but I have no idea how to do that.

**Comment by xentac** [comment]
I thought about it a bit more and I don't actually have that many payees in my file, so I added payee support.  It's a bit more rudimentary because I don't check to make sure you're completing in the right position (payee vs. narration), but it does work.

**Comment by xentac** [comment]
https://github.com/nathangrigg/vim-beancount/pull/22

PR created.
