### ISSUE TITLE
Beginning new line with o should align to postings

### ISSUE THREAD

**Issue by kubauk** [nathangrigg/vim-beancount#47]
When on the initial posting and you want to add a new posting it is convenient to use the o command to start a new line under the posting under the cursor. 

Currently when you use the o command the cursor is placed at the beginning of the line.

If the plugin detects that the new line being inserted under an existing posting, it should start the cursor at the position that matches the posting above (usually 2 spaces).

**Comment by kubauk** [comment]
Also the same should apply when pressing Enter on the initial posting when in Insert Mode

**Comment by xentac** [comment]
When I press 'o' on a posting, my vim-beancount does indent 2 spaces and always has. Similarly pressing Enter.

Relevant settings in vim might be

tabstop=2
softabstop=2
shiftwidth=2
expandtab

It looks like this whole file has to do with indenting of beancount files:

https://github.com/nathangrigg/vim-beancount/blob/8054352c43168ece62094dfc8ec510e347e19e3c/indent/beancount.vim

Which ends up setting "indentexpr=GetBeancountIndent(v:lnum)".

Did you verify that "filetype=beancount"?

**Comment by kubauk** [comment]
Hi,

Actually using this plugin was the primary reason for me starting to use VIM so my installation is bog standard (as in devoid of personal configuration). 

I've checked and the filetype is definitely beancount and the value of indentexpr matches what is in your comment.

I've checked the other values and my defaults were not the same as those above.

I resolved this by using the follow autocmd in my .vimrc:
autocmd FileType beancount setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab

**Question**: Should the plugin have set these values up for me or was it always my responsibility to set the values to match beancount's file format standard?

Doing this does fix the case when pressing o when the cursor is on the transaction line, however this still does not work for adding additional postings either with o or Enter for me

Given most of my transactions are generated using bean-extract, the transactions always have at least one posting before I start using vim to fill in the remaining posting so my main use case does not indent correctly.

Examples:

Working and next line is correctly indented:
2018-01-01 * "Memo"` (Press Enter in insert more or o in normal mode)

Not working
2018-01-01 * "Memo about some purchase"
<sp><sp>Assets:Current:BankA -103.54 GBP` (Press Enter in insert more or o in normal mode)

**Question**: Should indenting also work when adding the second posting to the transaction or is there a genuine bug?

I am using

> vim-beancount 8054352c43168ece62094dfc8ec510e347e19e3c

> VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  8 2018 19:47:36)
Included patches: 1-513
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl/dyn          +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           +python/dyn        +viminfo
+conceal           +linebreak         +python3/dyn       +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua/dyn           +ruby/dyn          +writebackup
+dialog_con_gui    +menu              +scrollbind        +X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       +xpm
-ebcdic            +mouseshape        +statusline        +xsmp_interact
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
+eval              +mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: " ~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: " ~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim81"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread    -O2 -g -pipe -Wall -Werror=format-security -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/python3.6m -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm -lnsl  -lselinux   -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -lnsl -ldl -lm -lcrypt -lutil -lc

**Comment by xentac** [comment]
It definitely works for me for lining up new postings as well as adding postings.

I've got a bunch of other settings that are unrelated but my :set looks like this

:set
--- Options ---
  background=dark     cursorline          ignorecase          scrollback=-1       syntax=beancount
  columns=123         expandtab           inccommand=split    shiftwidth=2        tabstop=2
  comments=b:;        foldmethod=syntax   lines=88            smartcase           window=87
  commentstring=;%s nohlsearch            scroll=43           softtabstop=2
  errorformat=%-G,%f:%l: %m,%-G %.%#
  fileencoding=utf-8
  filetype=beancount
  indentexpr=GetBeancountIndent(v:lnum)
  makeprg=bean-check %
  omnifunc=beancount#complete
  runtimepath=~/.config/nvim,~/.config/nvim/pack/minpac/start/vim-beancount,~/.config/nvim/pack/minpac/start/vim-airline,~/.config/nvim/pack/minpac/start/deoplete.nvim,/etc/xdg/nvim,~/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after
  statusline=%!airline#statusline(1)

Possibly this is a vim compatible mode problem. Try adding "set nocompatible" early in your vimrc. Many things are improved with that.

I can see your argument for setting the shiftwidth and everything by default. I'll consider it. I don't believe there's a strict requirement that beancount files use 2 spaces, but the convention is definitely there.

**Comment by kubauk** [comment]
I've got it working now. The secret was having autoindent set.
