### ISSUE TITLE
Autocompletion from an external file (or from all currently opened files)

### ISSUE THREAD

**Issue by redstreet** [nathangrigg/vim-beancount#5]
This is a feature request: since beancount supports the "include" directive, I maintain the list my accounts (as "open" directives) in a separate file. Because of this, autocomplete (the feature I need and use the most) doesn't quite work for me.

I was wondering if it's easy to either search over all files currently opened by vim (which is what vim-ledger does), or, ideally, be able to specify the file from which vim-beancount should build up the index of open accounts.

If this is difficult or if you aren't inclined to add this, it'd be great if you could give me some pointers. I don't know much vim scripting, but can look into it.

Thanks for vim-beancount, BTW. It's nice and very useful!

**Comment by nathangrigg** [comment]
My first inclination is to use bean-query to get a list of accounts. I'm a little concerned about parsing external files every time you need to do a completion, so this may require caching the result.

**Comment by redstreet** [comment]
Hmm, that sounds like a good idea, but at least on my machine, bean-query takes 15+ seconds to return, in part because of all the plugins it has to go through. Perhaps the thing to do would be to allow the user to run bean-query and list all opened accounts in a single file that acts as the cache?

If you like that idea, would you know how to read in such a cache file from your plugin? I could take a look if you pointed me to it.

**Comment by nathangrigg** [comment]
Okay, better idea is to just read the files ourselves.

**Comment by nathangrigg** [comment]
Pull request at #6 if you want to take a look or test it out. Still making a final decision about a couple of things, if you would like to weigh in there, you are welcome.

**Comment by redstreet** [comment]
Thanks again for this, this has been very helpful!
