### ISSUE TITLE
Autocomplete fails ("Pattern not found")

### ISSUE THREAD

**Issue by redstreet** [nathangrigg/vim-beancount#58]
Hi,
Autocomplete quit working for me at e831cf0 (Jason Chu Improved autocomplete).
It works until the immediately preceding commit (7a95550).

I get: ```-- Omni completion (^O^N^P) Pattern not found``` when I try to autocomplete an account.

How can I debug this issue? Thank you.

**Comment by redstreet** [comment]
@xentac : halp!

**Comment by xentac** [comment]
The actual autocompletion pattern never changed.

Have you tried a minimal vimrc? We could probably write a test if you have something minimal to test with.

This commit does use subprocess to call bean-query. Is bean-query available in the process space of vim?

**Comment by redstreet** [comment]
Here's the minimal test case. Note autocomplete fails only when b:beancount_root is set:

.vimrc:
```
au BufNewFile,BufRead *.bc   set filetype=beancount
autocmd FileType beancount let b:beancount_root="C:/Users/XX/Documents/x/open.bc"
```

open.bc:
```
1975-01-01 open Assets:Bank1
1975-01-01 open Assets:Bank2
```

test.bc:
```
2020-02-16 * "Test"
   Assets:<Ctrl-X><Ctrl-O>
```

**Comment by redstreet** [comment]
@xentac, are you able to reproduce the issue?

**Comment by xentac** [comment]
Using your minimal vimrc (plus some stuff to load the module), it worked for me.

The fact that beancount_root seems to be correlated in the problem implies to me that it's set wrong. In fact, if I change beancount_root to a file that doesn't exist, then it gives me the error you described. Perhaps we could raise that somewhere mentioning that beancount_root is set to something notexistent.

**Comment by xentac** [comment]
Does your beancount_root include spaces? It's possible that they're not getting escaped correctly in all the various layers and it's not loading the file correctly. The commit you linked to changed the way we load the beancount file from only parsing with regexps to querying using bean-query (which includes using subprocess and building a command line). Later on (if you have python3 enabled), we started loading the file directly into the python3 interpreter in vim which I would have expected to fix any "paths with spaces" problems.

**Comment by redstreet** [comment]
Ah, your description helped find the problem. I am using Cygwin, and I had to change:

```
let b:beancount_root="C:/Users/XXX/Documents/accounts/root.bc"
```
to:
```
let b:beancount_root="/home/XXX/accounts/root.bc"
```
with that commit. Everything now works. Thanks a bunch, @xentac, most appreciated! 👍
