### ISSUE TITLE
Definition of `beanKeyword`

### ISSUE THREAD

**Issue by srak289** [nathangrigg/vim-beancount#77]
I cannot find where you have defined `beanKeyword` ..

If it is implicit somehow then I'm simply showing my inexperience with vimscript / syntax highlighting.

I am working on making some of the highlighting more advanced as it is simply not to my liking but was confused when:
`grep -Irin beankeyword` only returned with lines from `syntax/beancount.vim` where `beanKeyword` was mentioned with `matchgroup=`.

Am I missing something?

**Comment by nathangrigg** [comment]
see `:h syn-matchgroup`. The start and end matches of the regular expressions defining the syntax region are marked as the matchgroup (`beanKeyword` in this case).
