### ISSUE TITLE
ImportError: cannot import name '_parser'

### ISSUE THREAD

**Issue by aleck2** [nathangrigg/vim-beancount#78]
error detected while processing function beancount#complete[17]..beancount#load_everything
ImportError: cannot import name '_parser' from 'beancount.parser' (/.../site-packages/beancount/parser/__init__.py)

**Comment by laleck** [comment]
Fixed by reinstalling beancount (v2) via pip. Make sure parser.so file exists in the beancount/parser directory (I had to change the suffix from .cpython-310-darwin.so to .so)
